### ISSUE TITLE
password is visible

### ISSUE THREAD

**Issue by kambleaa007** [darshu8/php-heroku#1]
Hi Darshan,
Everything is impressive and wonderful,
i don't know much about php,
I am really not sure about this
but
developers accessing your repository can easily look at your code
important information is exposed in `add.php` file code
like
1) server name $servername is `ec2-54-243-107-66.compute-1.amazonaws.com`
2) username
3) password (is most important)

can you do something to hide such information or forget about this issue if you already hided the  information.

Thanks,
Ashish

**Comment by darshu8** [comment]
Hello Ashish,
Thanks for feedback.
This repo is just a sample example to connect postgress with php on heroku platform.
there is no as such any personal data in db.
but in future what we can do is instead of using git we can directly deploy our application to heroku.

Thanks,
Darshan Jain.
